<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Анализатор страниц</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</head>

<body class="min-vh-100 d-flex flex-column">
    <header class="flex-shrink-0">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark px-3">
            <a class="navbar-brand" href="/">Анализатор страниц</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="/">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/urls">Сайты</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <?php if (count($flash) > 0) : ?>
        <?php foreach ($flash as $messages) : ?>
            <?php foreach ($messages as $message) : ?>
                <div class="alert alert-success" role="alert"><?= $message ?></div>
            <?php endforeach ?>
        <?php endforeach ?>
    <?php endif ?>


    <main class="flex-grow-1">
        <div class="container-lg mt-3">
            <h1>Сайт: <?= $data['name'] ?></h1>
            <div class="table-responsive">
                <table data-test="url" class="table table-bordered table-hover text-nowrap" data-test="url">
                    <tbody>
                        <tr>
                            <td>ID</td>
                            <td><?= $data['id'] ?></td>
                        </tr>
                        <tr>
                            <td>Имя</td>
                            <td><?= $data['name'] ?></td>
                        </tr>
                        <tr>
                            <td>Дата создания</td>
                            <td><?= $data['created_at'] ?></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <h2 class="mt-5 mb-3">Проверки</h2>
            <form method="post" action="/urls/<?= $data['id'] ?>/checks">
                <input type="submit" class="btn btn-primary" value="Запустить проверку">
            </form>
            <table class="table table-bordered table-hover" data-test="checks">
                <tbody>
                    <tr>
                        <th>ID</th>
                        <th>Код ответа</th>
                        <th>h1</th>
                        <th>title</th>
                        <th>description</th>
                        <th>Дата создания</th>
                    </tr>
                    <?php foreach ($checkData as $check) : ?>
                        <tr>
                            <td><?= $check['id'] ?? '' ?></td>
                            <td><?= $check['status_code'] ?? '' ?></td>
                            <td><?= $check['h1'] ?? '' ?></td>
                            <td><?= $check['title'] ?? '' ?></td>
                            <td><?= $check['description'] ?? '' ?></td>
                            <td><?= $check['created_at'] ?? '' ?></td>
                        </tr>
                    <?php endforeach ?>
                    <!--?php foreach ($checks as $check): ?-->
                </tbody>
            </table>
        </div>
    </main>
    <footer class="border-top py-3 mt-5 flex-shrink-0">
        <div class="container-lg">
            <div class="text-center">
                <a href="https://hexlet.io/pages/about" target="_blank">Hexlet</a>
            </div>
        </div>
    </footer>


</body>

</html>
